name: Auto Release and Build PyInstaller Executables

permissions:
  contents: write
  packages: write
  issues: read
  pull-requests: read

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Get version from MainApp.py
        id: get_version
        run: |
          VERSION=$(grep 'APP_VERSION' MainApp.py | head -1 | cut -d'"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create tag if not exists
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists"
          else
            git tag $TAG
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} $TAG
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          name: Release ${{ steps.create_tag.outputs.tag }}
          draft: false
          prerelease: false

  build-windows:
    needs: create-release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt pyinstaller

      - name: Build with PyInstaller (Windows)
        run: |
          python -m PyInstaller --onefile --windowed MainApp.py --name FNBHelper-Windows

      - name: Install PyUpdater
        run: |
          pip install pyupdater

      - name: Restore PyUpdater private key
        run: |
          mkdir -p keys
          echo "${{ secrets.PYUPDATER_PRIVATE_KEY }}" > keys/FNBHelper_priv.pem

      - name: Package with PyUpdater
        run: |
          pyupdater pkg --process

      - name: Upload to Release (Windows)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.create-release.outputs.tag_name }}
          files: |
            dist/FNBHelper-Windows.exe
            deploy/**

  build-macos:
    needs: create-release
    runs-on: macos-14  # Apple Silicon runner
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (Apple Silicon)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'arm64'

      - name: Set up venv and install dependencies (arm64)
        run: |
          python3 -m venv venv
          ./venv/bin/python -m pip install --upgrade pip
          ./venv/bin/python -m pip install -r requirements.txt pyinstaller pyqt6

      - name: Find Qt platforms plugin path
        id: qtpaths
        run: |
          PYTHON_BIN=./venv/bin/python
          echo "Using python: $PYTHON_BIN"
          $PYTHON_BIN -c 'import PyQt6.QtCore; print(list(PyQt6.QtCore.QLibraryInfo.paths(PyQt6.QtCore.QLibraryInfo.LibraryPath.PluginsPath)))'
          QT_PLUGINS=$($PYTHON_BIN -c 'import PyQt6.QtCore; print(PyQt6.QtCore.QLibraryInfo.path(PyQt6.QtCore.QLibraryInfo.LibraryPath.PluginsPath))')
          echo "QT_PLATFORMS=$QT_PLUGINS/platforms" >> $GITHUB_ENV
          echo "QT_PLATFORMS is: $QT_PLUGINS/platforms"

      - name: Ensure Qt platforms plugin exists
        run: |
          if [ ! -d "$QT_PLATFORMS" ]; then
            echo "ERROR: Qt 'platforms' directory not found at $QT_PLATFORMS"
            ls -l "${QT_PLATFORMS%/platforms}" || true
            exit 1
          fi

      - name: Build with PyInstaller (macOS arm64)
        run: |
          ./venv/bin/python -m PyInstaller --windowed MainApp.py --name FNBHelper-macOS \
            --add-data "$QT_PLATFORMS:platforms"

      - name: Zip .app bundle
        run: |
          cd dist
          zip -r FNBHelper-macOS.app.zip FNBHelper-macOS.app

      - name: Install PyUpdater
        run: |
          ./venv/bin/pip install pyupdater

      - name: Restore PyUpdater private key
        run: |
          mkdir -p keys
          echo "${{ secrets.PYUPDATER_PRIVATE_KEY }}" > keys/FNBHelper_priv.pem

      - name: Package with PyUpdater (macOS)
        run: |
          ./venv/bin/pyupdater pkg --process

      - name: Upload to Release (macOS)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.create-release.outputs.tag_name }}
          files: |
            dist/FNBHelper-macOS.app.zip
            deploy/**
