name: Build and Release PyInstaller Executables

on:
  push:
    tags:
      - 'v*'    # Only run on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build with PyInstaller (Windows)
        run: |
          pyinstaller --onefile --windowed MainApp.py --name FNBHelper-Windows

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: FNBHelper-Windows
          path: dist/FNBHelper-Windows.exe

      - name: Upload to Release (Windows)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/FNBHelper-Windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt pyinstaller

      - name: Build with PyInstaller (macOS)
        run: |
          pyinstaller --onefile --windowed MainApp.py --name FNBHelper-macOS

      - name: Upload artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: FNBHelper-macOS
          path: dist/FNBHelper-macOS

      - name: Upload to Release (macOS)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/FNBHelper-macOS
